apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: test-argocd-hook
    spec:
      restartPolicy: Never
      containers:
      - name: test-container
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Reading ConfigMap..."
            cat /config/message
            echo "Job completed successfully!"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: test-config
