apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-{{ now | date "20060102-150405" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # ArgoCD hook: This job will be created/recreated during the Sync phase
    argocd.argoproj.io/hook: Sync
    # Delete the job before creating a new one
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: test-argocd-hook
    spec:
      restartPolicy: Never
      containers:
      - name: test-container
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Reading ConfigMap..."
            cat /config/message
            echo "Job completed successfully!"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: test-config
